In [18]:
import os
import numpy as np
from numpy.linalg import matrix_power

# from matplotlib import pyplot
# from mpl_toolkits.mplot3d import Axes3D
# %matplotlib inline

In [19]:
os.chdir("/home/vanshb/P_Club/")
data = np.loadtxt(fname = "/home/vanshb/P_Club/housing.txt", delimiter='\t')
X, y = data[:, :3], data[:, 3]

m= y.size

In [20]:
one= np.ones(m)
X = np.concatenate((one[:,None], X), axis=1)
print(X)

[[ 1.     6.575  4.98  15.3  ]
 [ 1.     6.421  9.14  17.8  ]
 [ 1.     7.185  4.03  17.8  ]
 ...
 [ 1.     6.976  5.64  21.   ]
 [ 1.     6.794  6.48  21.   ]
 [ 1.     6.03   7.88  21.   ]]


In [21]:
for i in range(2,5):
    d=np.power(X,4)
print(d)

[[1.00000000e+00 1.86888694e+03 6.15059840e+02 5.47981281e+04]
 [1.00000000e+00 1.69985031e+03 6.97886477e+03 1.00387586e+05]
 [1.00000000e+00 2.66506061e+03 2.63766833e+02 1.00387586e+05]
 ...
 [1.00000000e+00 2.36824096e+03 1.01185065e+03 1.94481000e+05]
 [1.00000000e+00 2.13060121e+03 1.76319369e+03 1.94481000e+05]
 [1.00000000e+00 1.32211505e+03 3.85571451e+03 1.94481000e+05]]


In [22]:
def hypo(degree,X):
    x=X
    for i in range(2,degree+1):
#         for j in range(1,3):
        X_i= np.power(X,i)
        x=np.concatenate((x, X_i),axis=1)
    return x
# degree = int(input("Enter your value: "))
x=hypo(3,X)

with np.printoptions(threshold=np.inf):
    print(x)
# print(X[:, 2] * 2)

[[1.00000000e+00 6.57500000e+00 4.98000000e+00 1.53000000e+01
  1.00000000e+00 4.32306250e+01 2.48004000e+01 2.34090000e+02
  1.00000000e+00 2.84241359e+02 1.23505992e+02 3.58157700e+03]
 [1.00000000e+00 6.42100000e+00 9.14000000e+00 1.78000000e+01
  1.00000000e+00 4.12292410e+01 8.35396000e+01 3.16840000e+02
  1.00000000e+00 2.64732956e+02 7.63551944e+02 5.63975200e+03]
 [1.00000000e+00 7.18500000e+00 4.03000000e+00 1.78000000e+01
  1.00000000e+00 5.16242250e+01 1.62409000e+01 3.16840000e+02
  1.00000000e+00 3.70920057e+02 6.54508270e+01 5.63975200e+03]
 [1.00000000e+00 6.99800000e+00 2.94000000e+00 1.87000000e+01
  1.00000000e+00 4.89720040e+01 8.64360000e+00 3.49690000e+02
  1.00000000e+00 3.42706084e+02 2.54121840e+01 6.53920300e+03]
 [1.00000000e+00 7.14700000e+00 5.33000000e+00 1.87000000e+01
  1.00000000e+00 5.10796090e+01 2.84089000e+01 3.49690000e+02
  1.00000000e+00 3.65065966e+02 1.51419437e+02 6.53920300e+03]
 [1.00000000e+00 6.43000000e+00 5.21000000e+00 1.87000000e+01
  1

ValueError: operands could not be broadcast together with shapes (489,10) (489,) 

In [24]:
def Cost(x, y, theta):
    
    J = 0
    mat_mul= x.dot((theta.T))
    error= mat_mul-y
    error2= error*error
    final= error2.T
    i=0
    while(i<m):
#         if i%100==0:
#             print(i)
        J+= final[i]
        i=i+1
    J=J/(2*m)
    return J

/home/vanshb/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [32]:
def gradientDescent(x, y, theta, alpha, num_iters):
    m = y.shape[0]
    
    theta = theta.copy()
    
    J_h = [] # Use a python list to save cost in every iteration
    temp= np.ones(4*degree)
    for i in range(num_iters):
        for k in range(4*degree):
            if k==0 : 
                temp[0]= theta[0]-(alpha*sum([theta.dot(x[j].T)-y[j] for j in range(m)]))/m
            else:
                temp[k]= theta[k]-(alpha*sum([(theta.dot(x[j].T)-y[j])*x[j][k] for j in range(m)]))/m
        theta = temp
        J_h.append(Cost(x, y, theta))
    
    return theta, J_h

In [33]:
# initialize fitting parameters
theta = np.ones(4*degree)

# some gradient descent settings
iterations = 1500
alpha = 0.001

theta, J_h = gradientDescent(x ,y, theta, alpha, iterations)
# print('Theta found by gradient descent: {:.4f}, {:.4f}'.format(*theta))
print (theta)

/home/vanshb/.local/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in multiply
  
/home/vanshb/.local/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in double_scalars
  del sys.path[0]


[nan nan nan nan nan nan nan nan nan nan nan nan]


In [ ]:
from sklearn.preprocessing import PolynomialFeatures 
  
poly = PolynomialFeatures(degree = 4) 
X_poly = poly.fit_transform(X) 
  
poly.fit(X_poly, y) 
linreg = LinearRegression() 
linreg.fit(X_poly, y)

In [ ]:
linreg.predict(poly.fit_transform([9.77 20.45 12.2]))